### ISSUE TITLE
Ordering of Facets in Widget?

### ISSUE THREAD

**Issue by deckerweb** [cftp/facetious#14]
Is it possible to implement the ordering of the facets (fields) in the Widget? -- Or if used via template tags?

Currently it pulls a list of taxonomies but I need that in a different order on the frontend. How could I do that?

Thanks!

**Comment by johnbillion** [comment]
You can do this if you're using the template tag - it'll order the fields in the order that you lis them.

It's not currently possible to reorder fields if you're using the widget. We'll bear it in mind for a future version, though I'm not quite sure how it'd work from a UI perspective.

**Comment by simonwheatley** [comment]
You could deregister the built in widget, and register your own?

**Comment by deckerweb** [comment]
@johnbillion Thanks, great! Was not aware that is possible with template tags - I'll try that for sure. I am new to the plugin but lovin' it already! :)

@simonwheatley Thanks also, would be another great option, didn't think of it yet, but maybe I go that route for another project and make a little widget plugin :)
