### ISSUE TITLE
Not working properly

### ISSUE THREAD

**Issue by closemarketing** [cftp/facetious#21]
I'm using this plugin in a web page, but it does not give me correct results... It gives me all results.

Any idea?

**Comment by simonwheatley** [comment]
Can you give us more detail:
- What do you see
- What did you expect to see
- Steps to reproduce the problem

Screengrabs of the admin area and the front end will be helpful. URLs of the results page(s) will also be helpful.

**Comment by closemarketing** [comment]
Thanks Simon to reply.

It's very curious... It's only in one taxonomy:

http://s1.closemarketing.net/~beththalma/?page_id=725

When I use year. But not in others...

Regards.

**Comment by tomjn** [comment]
You appear to be using a page template for your taxonomy archive, rather than a taxonomy archive + `taxonomy-name.php` template or a post archive + `archive-pictures.php` template, are you making a query yourself using `get_posts`/`query_posts`/`WP_Query`?

I've identified an archive here:

http://s1.closemarketing.net/~beththalma/?post_type=pictures

**Comment by closemarketing** [comment]
Yes, It's a page template with the widget for Facetious. And then, it takes search.php template for showing the results.

**Comment by closemarketing** [comment]
The thing is that is one taxonomy Year that is not working. It's working for the others taxonomies...

**Comment by johnbillion** [comment]
Is your taxonomy named "year"? That won't work. A taxonomy named "year" will clash with WordPress' built-in date handling which includes year, month, and day. Your taxonomy likely won't work at all, regardless of Facetious.

Please try a different query variable for your taxonomy (for example, `archive_year`).

**Comment by closemarketing** [comment]
Very Nice! I will see then....
