### ISSUE TITLE
Plugin page header image

### ISSUE THREAD

**Issue by johnbillion** [cftp/facetious#3]
We should stick a header image on the plugin page at http://wordpress.org/extend/plugins/facetious/

**Comment by simonwheatley** [comment]
True, and I'd like to get someone to design us a bunch of these so we have everything look related.

**Comment by imsimond** [comment]
Are you thinking of some kind of 'house style' for these images?

**Comment by simonwheatley** [comment]
Exactly.  

## 

My life in WordPress:
http://profiles.wordpress.org/users/simonwheatley/

Sweet Interaction Ltd is Registered in England/Wales, no. 6610741
Registered office: 7 Malton Av, Manchester, M21 8AT
