### ISSUE TITLE
Enable a drop down to select post type

### ISSUE THREAD

**Issue by simonwheatley** [cftp/facetious#4]
Add an argument to the `fields` array which causes the display of a dropdown of post types. You should be able to specify which post types to display.

**Comment by simonwheatley** [comment]
Uncovered an issue whereby the `page` `post_type` is not respected in the search, looks like it's an issue caused by something in core, not necessarily something in Facetious.

**Comment by simonwheatley** [comment]
> Uncovered an issue whereby the page post_type is not respected in the search, looks like it's an issue caused by something in core, not necessarily something in Facetious.

If a `post_type` value is set for a post type which is not `publicly_queryable` then WordPress [unsets that value](http://core.trac.wordpress.org/browser/tags/3.5.1/wp-includes/class-wp.php#L287) during the request parsing. Should we override WordPress in this respect, so that it is possible to query post types which are not `publicly_queryable`?

/cc @johnbillion

**Comment by simonwheatley** [comment]
Also need to check we're happy with the `values` argument I've added to the arguments which can be supplied for a particular field (though it's only respected by `pt` field types right now.

**Comment by johnbillion** [comment]
> Uncovered an issue whereby the page post_type is not respected in the search, looks like it's an issue caused by something in core, not necessarily something in Facetious.

http://core.trac.wordpress.org/ticket/17040

**Comment by simonwheatley** [comment]
Completed.
