### ISSUE TITLE
Searches with no keyword but with a `type` trigger notices

### ISSUE THREAD

**Issue by simonwheatley** [cftp/facetious#5]
WordPress is treating the search as though it were a post type archive, but choking when this isn't the case.

Example URL to cause the issue: `http://nao.simonwheatley.co.uk/search/type/report/sector/children-and-families/`

This could be because `is_search` isn't set to true on `WP_Query` when the search keyword isn't present.

**Comment by simonwheatley** [comment]
I considered faking it, and always adding a keyword of " " (i.e. a space) if there was no keyword. This seems hacky though.

**Comment by johnbillion** [comment]
In general I think this is a good idea, but what happens to - for example - the default theme's search template when the search query var is empty? Will you end up with something like `Search results for ""`?

**Comment by simonwheatley** [comment]
Good point. I think we need to look at:
- Filtering the text in that
- Dealing similarly with some of the breadcrumb plugins (which I've noticed are an issue on the current site we're working on _taps nose_)

**Comment by simonwheatley** [comment]
> In general I think this is a good idea, but what happens to - for example - the default theme's search template when the search query var is empty? Will you end up with something like Search results for ""?

Related #11
