### ISSUE TITLE
301 rather than 302?

### ISSUE THREAD

**Issue by simonwheatley** [cftp/facetious#6]
Should Facetious use 301 rather than 302 URLs for [the redirects](https://github.com/cftp/facetious/blob/master/facetious.php#L149)? Discuss.

From the top of my head:

**Pros**
- Site owners can create URLs which Google will follow

**Cons**
- Facetious gets turned off, and the URLs stop working

**Comment by johnbillion** [comment]
+1 on using 301s. The pro outweighs the con. The URLs will stop working anyway if Facetious is deactivated, regardless of whether the URLs are indexed by Google or not (eg. an author could link to search results in blogs posts etc).
