### ISSUE TITLE
Add is_facetious conditional check function

### ISSUE THREAD

**Issue by simonwheatley** [cftp/facetious#8]
See https://github.com/cftp/facetious/commit/508a034b7925f3ed04778155b8303c8a524fc209

Any objections?

**Comment by johnbillion** [comment]
Nope.

**Comment by JiveDig** [comment]
Is this included somewhere?  I would like to only display (or not display) content in my template based on whether it's a facetious search or not.

Something like: if( ! is_facetious() ) {

So I could only show some content on the main archive, not if it's a search

**Comment by JiveDig** [comment]
Turns out this is already possible...
global $wp;
if ( ! isset( $wp->query_vars[ 'facetious_post_type' ] ) ) {

**Comment by johnbillion** [comment]
@JiveDig There's a template function included in Facetious that you can use: `is_facetious()`.

**Comment by JiveDig** [comment]
Tested this in a conditional if ( is_facetious() ) {} and it did not work.  Tested on 2 separate installs. Both running Genesis if that matters.
